### ISSUE TITLE
Unable to load demo data in Docker

### ISSUE THREAD

**Issue by sanderdekroon** [maykinmedia/open-inwoner#307]
### Describe the bug
I am unable to load the demo data (as described in [/docs/install/dev.rst](https://github.com/maykinmedia/open-inwoner/blob/develop/docs/install/dev.rst)) within the Docker container.

### To Reproduce
1. `docker-compose up -d`
2. `docker exec -it open-inwoner-web-1 bash`
3. `python src/manage.py loaddata demo`

An error occurs:
```sh
System check identified some issues:

WARNINGS:
?: (utils.W001) Directory /app/src/open_inwoner/conf/app does not contain an `__init__.py` fileapp
	HINT: Consider adding this module to make sure tests are picked up
timeline_logger.TimelineLog.extra_data: (fields.W904) django.contrib.postgres.fields.JSONField is deprecated. Support for it (except in historical migrations) will be removed in Django 4.0.
	HINT: Use django.db.models.JSONField instead.
CommandError: No fixture named 'demo' found.
```

I'm running the most recent version from the develop branch.

**Comment by sanderdekroon** [comment]
Somebody? Anybody?

**Comment by alextreme** [comment]
The dev.rst is a default section of our installation documentation, I've removed the mention of the demo data as it's currently not available (or necessary) to start the project.
